### PR TITLE
Feature/dockerize development environment

### PR DESCRIPTION
**Pull request by lsbCoding**
Pull request for issue #18

### CODE REVIEW

**Review by srepetsk — APPROVED** [review]
Thanks for the containerization! This will definitely make standing MH up for beginners easier.

**Comment by lsbCoding** [comment]
> Thanks for the containerization! This will definitely make standing MH up for beginners easier.

Happy to help. Looks like it'll need the conflict resolution. I'll also need to incorporate the changes you made with the C11 station update. I can probably add those in another branch once this merges.

**Comment by lsbCoding** [comment]
Sorry just noticed you added some changes from the C11 branch already.

I don't believe 01_insert_c11.sql will work as intended for fresh docker container spin ups. When the postgres container runs the numbered init scripts during it's startup the tables have not yet been created by spring boot. There would be two options to fix that. Either run an additional "docker -it bash" command to run the insert_c11 script after the station_to_station_travel_time script or update the station_to_station script to include the insert_c11 changes.

Additionally, I'm not sure if you were waiting for me to fix the logback file conflict, but I know have permissions in github to do that. I can push an update to the branch to resolve if you'd like.

**Comment by srepetsk** [comment]
I ended up adding the changes from the [01_insert_c11.sql](https://github.com/srepetsk/metrohero-server/blob/develop/sql/01_insert_c11.sql) file over into the main [station_to_station_travel_time.sql](https://github.com/srepetsk/metrohero-server/blob/develop/sql/station_to_station_travel_time.sql) file; there's not actually a good reason to modify the table vice a drop and reload. Would it be easier if the 01_insert_c11.sql file be removed, so as not to break the Postgres container?

I'm happy to defer to you to resolve the logback conflict, otherwise I can do it as well.

(Also if it's easier, I'm more active/able to respond more quickly over on the MH Discord - https://discord.com/channels/1127224836003995710/1127224836717023274)

**Comment by lsbCoding** [comment]
> https://discord.com/channels/1127224836003995710/1127224836717023274

I've never used discord, but I just attempted to access your server and the link doesn't seem to be working. My discord account is lsbD1scord, if that helps.

The insert_c11 script can stay as long as we aren't mounting it into the container with a volume. That way the postgres will never see it. 

I can update the logback. Are you good with the name change from logback.xml to logback-spring.xml?

**Comment by lsbCoding** [comment]
As a newbie to working with github, I fear I've made a terrible mistake! Working to remedy the situation!

**Comment by srepetsk** [comment]
Ha, I'm newer to DIscord as well; maybe https://discord.gg/PCZwXtyX might work for you. (I can't seem to invite you by username)

**Pull request closed without merging**
